server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      mvc:
        routes:
          - id: order-service
            uri: http://order-service.default.svc.cluster.local
            predicates:
              - Path=/orders/**
          - id: inventory-service
            uri: http://inventory-service.default.svc.cluster.local
            predicates:
              - Path=/inventory/**