server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      mvc:
        routes:
          - id: order-service
            uri: http://order-service:8081
            predicates:
              - Path=/orders/**
          - id: inventory-service
            uri: http://inventory-service:8082
            predicates:
              - Path=/inventory/**