apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-inventory-db
spec:
  selector:
    matchLabels:
      app: mongo-inventory-db
  template:
    metadata:
      labels:
        app: mongo-inventory-db
    spec:
      containers:
        - name: mongo-inventory-db
          image: mongo:7.0-jammy
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_DATABASE
                  name: mongo-inventory-db-config
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-inventory-db
spec:
  selector:
    app: mongo-inventory-db
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-inventory-db-config
data:
  MONGO_INITDB_DATABASE: "inventory"