server:
  port: 8081

spring:
  application:
    name: order-service

  data:
    mongodb:
      uri: mongodb://mongo-order-db:27017/orders

base-uri:
  inventory-service: http://inventory-service:8082/inventory